### ISSUE TITLE
Exception handler (WEB) 

### ISSUE THREAD

**Issue by helmut-winkelbach** [FriendsOfTYPO3/widgets#20] opened 2020-05-02 16:20 UTC
# Bug Report
* [x ] Can you reproduce the problem on TYPO3 v10.4.1 with Ext. widgets

## Description
[Description of the bug]
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1526127158: Uid must be a positive integer, given. | InvalidArgumentException thrown in file /kunden/174878_70794/rp-hosting/5712/6712/typo3cms/typo3_src-10.4.1/typo3/sysext/backend/Classes/ViewHelpers/Link/EditRecordViewHelper.php in line 84. Requested URL: https://www.erfurt-bahai.de/typo3/index.php?route=%%2Fajax%%2Fdashboard%%2Fwidget%%2Fcontent&token=--AnonymizedToken--&widget=widgets-pagesWithoutMetaDescription
## Steps to Reproduce

1. [First Step]
Use Dashboard =widgets-pagesWithoutMetaDescription

**Comment by PhilippKuhlmay** [comment] 2020-05-02 17:21
This is the same bug as #19

**Comment by haassie** [comment] 2020-05-05 08:59
As this is a duplicate of #19, I will close this issue.

**Closed by haassie** 2020-05-05 08:59 UTC
Labels: bug
